### ISSUE TITLE
Error when running demo.R

### ISSUE THREAD

**Issue by stefanocoretta** [IPS-LMU/soundChangeR#1]
OS: Linux Ubuntu (#84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019)
R version 3.6.2 (2019-12-12)
RStudio 1.2.5033

https://github.com/IPS-LMU/ABM/blob/4f405bd89a60c4d9c2e4f917df927746f2e52645/functions/demo.R#L119

The above line throws the following error:

```
Error in source(textConnection(file.lines.collapsed), ...) : 
  textConnection(file.lines.collapsed):41:0: unexpected end of input
39:     cl <- makeCluster(numCores, type = "FORK")
   ^
```

`source_part(file.path("Rcmd", "ABMmain.R"), 21, 75)` fixes the problem (the range should be `21, 75` rather than `21, 65`).

Maybe soft-coding the beginning and end is better in case users add/remove lines from `ABMmain.R`?

**Comment by johannacronenberg** [comment]
thanks, will take care of this!

**Comment by johannacronenberg** [comment]
@stefanocoretta I couldn't replicate the problem, but anyway, I have now soft-coded the beginning and end as you suggested. Please let me know if the bugfix doesn't work!

**Comment by stefanocoretta** [comment]
Ok, weird you can't reproduce it because the line numbers in the line above from the demo script do not correspond to the line numbers in `ABMmain.R` which include the `if` statement (they `if` statement goes from line 52 to line 72, not to line 65, that's why the error when sourcing, the if statement is not complete).

I can't see the changes on the master branch, are you working on a separate branch?

**Comment by johannacronenberg** [comment]
Sorry I had to setup this repo as a new remote first, now the changes are on master. I was also working with an older version of `ABMmain.R` (hadn't noticed that Michele had changed something). But now the demo works fine, hopefully :)

**Comment by stefanocoretta** [comment]
Yes, it works fine now. :)
