### ISSUE TITLE
Object 'condition' not found

### ISSUE THREAD

**Issue by PeterGilles** [IPS-LMU/soundChangeR#10]
Dear all,
I am trying to replicate and understand this ABM, but when running `demo.R` or `analysis.R` after `Rcmd/ABMmain.R` (with the default parameters) I am getting some errors. The models `ABM2021xxxx` are created in `logDir` and I can display the first box plot. 

The next step (row 143 in `demo.R`) breaks off with the error and I cannot continue:

    The next plots shows the development of the feature values over time, i.e. nr of interactions.
    Fehler in eval(bysub, x, parent.frame()) : 
      Objekt 'condition' nicht gefunden

Thanks.

**Comment by johannacronenberg** [comment]
Hello, 

thank you so much for your interest in our ABM! Unfortunately, the demo.R and analysis.R scripts are not up to date, that is why these errors occur. I am planning on updating them in late August -- sorry for not being able to fix these errors earlier.

All the best,
Johanna

**Comment by johannacronenberg** [comment]
Dear Prof. Gilles, 

this is just to inform you that the promised updates to the repository will take a little longer as we are currently working on the basic structure of the code. I'll let you know when we are done with it.

All the best,
Johanna

**Comment by PeterGilles** [comment]
Thank you!

**Comment by johannacronenberg** [comment]
This issue was solved in the re-structuring of the code over the last year.
