### ISSUE TITLE
write interaction log more often

### ISSUE THREAD

**Issue by MJochim** [IPS-LMU/soundChangeR#3]
The interaction log is currently only written at the end of the simulation. It has happened to me that long-running simulations have crashed (was my own fault in both cases and had to do with disk space running out). It might be good to write the interaction log to disk once in a while, maybe with every snapshot. This way it would not be lost completely after a crash.

**Comment by johannacronenberg** [comment]
This issue has been addressed in commit 4b1f703 (branch GMM). The interaction log is now written on every snapshot.
